### ISSUE TITLE
module-user style tweaks

### ISSUE THREAD

**Issue by austinrivas** [LumaPictures/meteor-luma-ui#6]
remove striped class from tasks table

change this to selector green

``` css
.nav-pills > li.active > a,
.nav-pills > li.active > a:hover,
.nav-pills > li.active > a:focus {
  background-color: #3CA2BB;
  border-color: #3CA2BB;
}
```

remove label form top_option_row_bar_form
