### ISSUE TITLE
routes in db - translations

### ISSUE THREAD

**Issue by rudolfb** [LumaPictures/meteor-luma-ui#8]
Hi Austin,

I hope this is the correct forum to ask questions about meteor-luma-ui. Thanks for the really great UI and all the work you have put into this.

In meteor-luma-ui you store the routes in the database. Your routes contain text information that is displayed on the screen, e.g.

```
,{
    route: "invoiceList"
    path: "/invoices/list"
    controller: 'ExampleController'
    page:
      title: "Invoice List"   <- language specific
      subtitle: "Time to break some kneecaps."   <- language specific
    breadcrumbs: [
      title: "Invoices"   <- language specific
      route: 'invoices'
    ]
  }
```

Do you have a suggestion how to implement translatable texts in the context of your routes framework?

If the routes were not stored in the db one could translate the texts on the fly. In a multi-language application this type of problem would have to be resolved. Or can one move the title and subtitle information outside of the router.coffee?

Regards

Rudolf Bargholz
